server {
  listen 80; 	# Standardport von nginx
  server_name localhost; 	# Servername


  location / { 	# alle Anfragen an das Root-Verzeichnis
    root /usr/share/nginx/html; 	# Standardverzeichnis für statische Dateien
    index index.html; 	# Startseite
  }


  location /api/ { 	# alle /api/-Anfragen an das Backend   weiterleiten
    proxy_pass http://taskmanager:6000/api/; 	# Proxy zur App in Compose-Netzwerk
    proxy_set_header Host $host; 	# ursprünglichen Host weiterleiten
    proxy_set_header X-Real-IP $remote_addr; 	# ursprüngliche IP-Adresse weiterleiten
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;	# Proxy-Kette
    proxy_set_header X-Forwarded-Proto $scheme;	# HTTP/HTTPS-Schema weiterleiten
  }
}
